plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

baseurl: /netlify-cms-jekyll

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
