backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "images/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - {
          label: "Author",
          collection: "authors",
          name: "author",
          widget: "relation",
          searchFields: ["name"],
          valueField: "name",
          default: "blog",
        }
      - { label: "Body", name: "body", widget: "markdown" }
